import { MigrationInterface, QueryRunner } from "typeorm";

export class AddLastDietLevelIncreasedAt1790063705912 implements MigrationInterface {
    name = 'AddLastDietLevelIncreasedAt1790063705912'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "treatment_orders" DROP CONSTRAINT "FK_treatment_orders_ordered_by"`);
        await queryRunner.query(`ALTER TABLE "treatment_orders" DROP CONSTRAINT "FK_treatment_orders_case"`);
        await queryRunner.query(`ALTER TABLE "patient_cases" DROP CONSTRAINT "FK_patient_cases_active_treatment_order"`);
        await queryRunner.query(`ALTER TABLE "vital_signs" DROP CONSTRAINT "FK_vital_signs_recorded_by"`);
        await queryRunner.query(`ALTER TABLE "vital_signs" DROP CONSTRAINT "FK_vital_signs_case"`);
        await queryRunner.query(`ALTER TABLE "survey_questions" DROP CONSTRAINT "FK_survey_questions_questionnaire_version"`);
        await queryRunner.query(`ALTER TABLE "patient_assessments" DROP CONSTRAINT "FK_patient_assessments_questionnaire_version"`);
        await queryRunner.query(`ALTER TABLE "app_engagement_logs" DROP CONSTRAINT "FK_app_engagement_logs_case_id"`);
        await queryRunner.query(`ALTER TABLE "pod_protocols" DROP CONSTRAINT "FK_d5a013f726d32f46601250c110e"`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" DROP CONSTRAINT "FK_assessment_tasks_assessment"`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" DROP CONSTRAINT "FK_assessment_tasks_case"`);
        await queryRunner.query(`ALTER TABLE "pod_protocol_tracking_logs" DROP CONSTRAINT "FK_pod_tracking_logs_changed_by"`);
        await queryRunner.query(`ALTER TABLE "pod_protocol_tracking_logs" DROP CONSTRAINT "FK_pod_tracking_logs_case_id"`);
        await queryRunner.query(`ALTER TABLE "room_nurse_assignments" DROP CONSTRAINT "FK_room_nurse_assignments_nurse"`);
        await queryRunner.query(`ALTER TABLE "health_education_pod_contents" DROP CONSTRAINT "FK_health_education_pod_contents_operation_type"`);
        await queryRunner.query(`ALTER TABLE "user_devices" DROP CONSTRAINT "FK_user_devices_user_id"`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" DROP CONSTRAINT "FK_care_observation_tasks_treatment_order"`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" DROP CONSTRAINT "FK_care_observation_tasks_template"`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" DROP CONSTRAINT "FK_care_observation_tasks_case"`);
        await queryRunner.query(`ALTER TABLE "care_observation_entries" DROP CONSTRAINT "FK_care_observation_entries_observed_by"`);
        await queryRunner.query(`ALTER TABLE "care_observation_entries" DROP CONSTRAINT "FK_care_observation_entries_task"`);
        await queryRunner.query(`ALTER TABLE "monitoring_alerts" DROP CONSTRAINT "FK_monitoring_alerts_handled_by"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_survey_questions_version_dimension"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_patient_assessments_case_pod_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_patient_assessments_case_source"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_assessment_tasks_pending_window"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_room_nurse_assignments_nurse"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_health_education_pod_contents_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_devices_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_devices_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_care_observation_tasks_one_open_per_case"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_care_observation_entries_task_observed_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_monitoring_alerts_pending_red_case"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_monitoring_alerts_handled_red_unlock_notification"`);
        await queryRunner.query(`ALTER TABLE "question_options" DROP CONSTRAINT "CHK_question_options_triage_level"`);
        await queryRunner.query(`ALTER TABLE "patient_assessments" DROP CONSTRAINT "CHK_patient_assessments_type"`);
        await queryRunner.query(`ALTER TABLE "patient_assessments" DROP CONSTRAINT "CHK_patient_assessments_scheduled_slot"`);
        await queryRunner.query(`ALTER TABLE "patient_assessments" DROP CONSTRAINT "CHK_patient_assessments_triage_verdict_snapshot"`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" DROP CONSTRAINT "CHK_assessment_tasks_slot"`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" DROP CONSTRAINT "CHK_assessment_tasks_status"`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" DROP CONSTRAINT "CHK_assessment_tasks_window"`);
        await queryRunner.query(`ALTER TABLE "care_observation_sheet_templates" DROP CONSTRAINT "CHK_care_observation_sheet_templates_code"`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" DROP CONSTRAINT "CHK_care_observation_tasks_status"`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" DROP CONSTRAINT "UQ_assessment_tasks_case_pod_slot"`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" DROP COLUMN "missed_at"`);
        await queryRunner.query(`ALTER TABLE "monitoring_alerts" DROP COLUMN "handling_started_at"`);
        await queryRunner.query(`ALTER TABLE "monitoring_alerts" DROP COLUMN "trigger_details"`);
        await queryRunner.query(`ALTER TABLE "patient_cases" ADD "last_diet_level_increased_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" ADD "missed_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`COMMENT ON COLUMN "patient_cases"."eras_completed" IS NULL`);
        await queryRunner.query(`ALTER TABLE "health_education_pod_contents" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "health_education_pod_contents" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "health_education_pod_contents" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "health_education_pod_contents" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "care_observation_sheet_templates" ALTER COLUMN "checklist_items" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" DROP CONSTRAINT "assessment_tasks_assessment_id_key"`);
        await queryRunner.query(`ALTER TABLE "care_observation_entries" ALTER COLUMN "findings" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "treatment_orders" ADD CONSTRAINT "FK_64c20d27abfd0752a253dc62e84" FOREIGN KEY ("case_id") REFERENCES "patient_cases"("case_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_orders" ADD CONSTRAINT "FK_72e95f3f1acb437bec04837c47b" FOREIGN KEY ("ordered_by_user_id") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_cases" ADD CONSTRAINT "FK_2f6757f1a8408b8a3b0e08ed90b" FOREIGN KEY ("active_treatment_order_id") REFERENCES "treatment_orders"("treatment_order_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vital_signs" ADD CONSTRAINT "FK_9ffbf02512ebf7b1cb2594fbcee" FOREIGN KEY ("case_id") REFERENCES "patient_cases"("case_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vital_signs" ADD CONSTRAINT "FK_204a383234f338397b4c0a60fb1" FOREIGN KEY ("recorded_by_user_id") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_engagement_logs" ADD CONSTRAINT "FK_82d031d5f71525f4d88d80b170a" FOREIGN KEY ("case_id") REFERENCES "patient_cases"("case_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pod_protocols" ADD CONSTRAINT "FK_d5a013f726d32f46601250c110e" FOREIGN KEY ("operation_type_id") REFERENCES "operation_types"("operation_type_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" ADD CONSTRAINT "FK_a082a53040340df8b9b8882d8d7" FOREIGN KEY ("case_id") REFERENCES "patient_cases"("case_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" ADD CONSTRAINT "FK_62f209f47c090dd5fa4af064485" FOREIGN KEY ("assessment_id") REFERENCES "patient_assessments"("assessment_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pod_protocol_tracking_logs" ADD CONSTRAINT "FK_1754470289c2b1365a85543b5b5" FOREIGN KEY ("case_id") REFERENCES "patient_cases"("case_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pod_protocol_tracking_logs" ADD CONSTRAINT "FK_c2b02288c5aa304e995e78a3f40" FOREIGN KEY ("changed_by") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_nurse_assignments" ADD CONSTRAINT "FK_7f9df6833ce4a7be9abe923d945" FOREIGN KEY ("nurse_user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_devices" ADD CONSTRAINT "FK_28bd79e1b3f7c1168f0904ce241" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" ADD CONSTRAINT "FK_997363eef34d3e0a77f2367084e" FOREIGN KEY ("case_id") REFERENCES "patient_cases"("case_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" ADD CONSTRAINT "FK_5ef4be83ff39b95808f46be7a35" FOREIGN KEY ("template_id") REFERENCES "care_observation_sheet_templates"("template_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" ADD CONSTRAINT "FK_dc69d65deaca0cf34f858eddbbf" FOREIGN KEY ("treatment_order_id") REFERENCES "treatment_orders"("treatment_order_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "care_observation_entries" ADD CONSTRAINT "FK_d6bd68cb119c1d0f889aa8601ec" FOREIGN KEY ("task_id") REFERENCES "care_observation_tasks"("task_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "care_observation_entries" ADD CONSTRAINT "FK_ea912579879680b390adbb07baa" FOREIGN KEY ("observed_by_user_id") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "monitoring_alerts" ADD CONSTRAINT "FK_dea2f9488c312833fa9815dca87" FOREIGN KEY ("handled_by_user_id") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "monitoring_alerts" DROP CONSTRAINT "FK_dea2f9488c312833fa9815dca87"`);
        await queryRunner.query(`ALTER TABLE "care_observation_entries" DROP CONSTRAINT "FK_ea912579879680b390adbb07baa"`);
        await queryRunner.query(`ALTER TABLE "care_observation_entries" DROP CONSTRAINT "FK_d6bd68cb119c1d0f889aa8601ec"`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" DROP CONSTRAINT "FK_dc69d65deaca0cf34f858eddbbf"`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" DROP CONSTRAINT "FK_5ef4be83ff39b95808f46be7a35"`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" DROP CONSTRAINT "FK_997363eef34d3e0a77f2367084e"`);
        await queryRunner.query(`ALTER TABLE "user_devices" DROP CONSTRAINT "FK_28bd79e1b3f7c1168f0904ce241"`);
        await queryRunner.query(`ALTER TABLE "room_nurse_assignments" DROP CONSTRAINT "FK_7f9df6833ce4a7be9abe923d945"`);
        await queryRunner.query(`ALTER TABLE "pod_protocol_tracking_logs" DROP CONSTRAINT "FK_c2b02288c5aa304e995e78a3f40"`);
        await queryRunner.query(`ALTER TABLE "pod_protocol_tracking_logs" DROP CONSTRAINT "FK_1754470289c2b1365a85543b5b5"`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" DROP CONSTRAINT "FK_62f209f47c090dd5fa4af064485"`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" DROP CONSTRAINT "FK_a082a53040340df8b9b8882d8d7"`);
        await queryRunner.query(`ALTER TABLE "pod_protocols" DROP CONSTRAINT "FK_d5a013f726d32f46601250c110e"`);
        await queryRunner.query(`ALTER TABLE "app_engagement_logs" DROP CONSTRAINT "FK_82d031d5f71525f4d88d80b170a"`);
        await queryRunner.query(`ALTER TABLE "vital_signs" DROP CONSTRAINT "FK_204a383234f338397b4c0a60fb1"`);
        await queryRunner.query(`ALTER TABLE "vital_signs" DROP CONSTRAINT "FK_9ffbf02512ebf7b1cb2594fbcee"`);
        await queryRunner.query(`ALTER TABLE "patient_cases" DROP CONSTRAINT "FK_2f6757f1a8408b8a3b0e08ed90b"`);
        await queryRunner.query(`ALTER TABLE "treatment_orders" DROP CONSTRAINT "FK_72e95f3f1acb437bec04837c47b"`);
        await queryRunner.query(`ALTER TABLE "treatment_orders" DROP CONSTRAINT "FK_64c20d27abfd0752a253dc62e84"`);
        await queryRunner.query(`ALTER TABLE "care_observation_entries" ALTER COLUMN "findings" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" ADD CONSTRAINT "assessment_tasks_assessment_id_key" UNIQUE ("assessment_id")`);
        await queryRunner.query(`ALTER TABLE "care_observation_sheet_templates" ALTER COLUMN "checklist_items" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "health_education_pod_contents" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "health_education_pod_contents" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "health_education_pod_contents" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "health_education_pod_contents" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "patient_cases"."eras_completed" IS 'Indicates whether the patient has completed the ERAS protocol (reached max POD)'`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" DROP COLUMN "missed_at"`);
        await queryRunner.query(`ALTER TABLE "patient_cases" DROP COLUMN "last_diet_level_increased_at"`);
        await queryRunner.query(`ALTER TABLE "monitoring_alerts" ADD "trigger_details" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "monitoring_alerts" ADD "handling_started_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" ADD "missed_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" ADD CONSTRAINT "UQ_assessment_tasks_case_pod_slot" UNIQUE ("case_id", "pod_context", "scheduled_slot")`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" ADD CONSTRAINT "CHK_care_observation_tasks_status" CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'SUPERSEDED'::character varying, 'COMPLETED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "care_observation_sheet_templates" ADD CONSTRAINT "CHK_care_observation_sheet_templates_code" CHECK (((code)::text = ANY ((ARRAY['LEVEL_1_SHEET'::character varying, 'LEVEL_2_3_SHEET'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" ADD CONSTRAINT "CHK_assessment_tasks_window" CHECK ((opens_at < closes_at))`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" ADD CONSTRAINT "CHK_assessment_tasks_status" CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'MISSED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" ADD CONSTRAINT "CHK_assessment_tasks_slot" CHECK (((scheduled_slot)::text = ANY ((ARRAY['MORNING'::character varying, 'AFTERNOON'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "patient_assessments" ADD CONSTRAINT "CHK_patient_assessments_triage_verdict_snapshot" CHECK (((triage_verdict_snapshot IS NULL) OR ((triage_verdict_snapshot)::text = ANY ((ARRAY['GREEN'::character varying, 'YELLOW'::character varying, 'RED'::character varying])::text[]))))`);
        await queryRunner.query(`ALTER TABLE "patient_assessments" ADD CONSTRAINT "CHK_patient_assessments_scheduled_slot" CHECK (((((assessment_type)::text = 'SCHEDULED'::text) AND (scheduled_slot IS NULL)) OR (((assessment_type)::text = 'TRIGGERED'::text) AND (scheduled_slot IS NULL)) OR ((scheduled_slot)::text = ANY ((ARRAY['MORNING'::character varying, 'AFTERNOON'::character varying])::text[]))))`);
        await queryRunner.query(`ALTER TABLE "patient_assessments" ADD CONSTRAINT "CHK_patient_assessments_type" CHECK (((assessment_type)::text = ANY ((ARRAY['SCHEDULED'::character varying, 'TRIGGERED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "question_options" ADD CONSTRAINT "CHK_question_options_triage_level" CHECK (((option_triage_level IS NULL) OR ((option_triage_level)::text = ANY ((ARRAY['GREEN'::character varying, 'YELLOW'::character varying, 'RED'::character varying])::text[]))))`);
        await queryRunner.query(`CREATE INDEX "IDX_monitoring_alerts_handled_red_unlock_notification" ON "monitoring_alerts" ("triggered_at") WHERE (((alert_type)::text = 'RED'::text) AND ((status)::text = 'HANDLED'::text) AND (unlock_notified_at IS NULL))`);
        await queryRunner.query(`CREATE INDEX "IDX_monitoring_alerts_pending_red_case" ON "monitoring_alerts" ("case_id", "triggered_at") WHERE (((alert_type)::text = 'RED'::text) AND ((status)::text = 'PENDING_REVIEW'::text))`);
        await queryRunner.query(`CREATE INDEX "IDX_care_observation_entries_task_observed_at" ON "care_observation_entries" ("task_id", "observed_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_care_observation_tasks_one_open_per_case" ON "care_observation_tasks" ("case_id") WHERE ((status)::text = 'OPEN'::text)`);
        await queryRunner.query(`CREATE INDEX "IDX_user_devices_is_active" ON "user_devices" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_devices_user_id" ON "user_devices" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_health_education_pod_contents_active" ON "health_education_pod_contents" ("pod_day", "operation_type_id") WHERE (is_active = true)`);
        await queryRunner.query(`CREATE INDEX "IDX_room_nurse_assignments_nurse" ON "room_nurse_assignments" ("nurse_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_assessment_tasks_pending_window" ON "assessment_tasks" ("opens_at", "closes_at") WHERE ((status)::text = 'PENDING'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_patient_assessments_case_source" ON "patient_assessments" ("case_id", "evaluation_datetime", "source") `);
        await queryRunner.query(`CREATE INDEX "IDX_patient_assessments_case_pod_time" ON "patient_assessments" ("case_id", "evaluation_datetime", "pod_context") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_survey_questions_version_dimension" ON "survey_questions" ("questionnaire_version_id", "clinical_dimension") WHERE (clinical_dimension IS NOT NULL)`);
        await queryRunner.query(`ALTER TABLE "monitoring_alerts" ADD CONSTRAINT "FK_monitoring_alerts_handled_by" FOREIGN KEY ("handled_by_user_id") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "care_observation_entries" ADD CONSTRAINT "FK_care_observation_entries_task" FOREIGN KEY ("task_id") REFERENCES "care_observation_tasks"("task_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "care_observation_entries" ADD CONSTRAINT "FK_care_observation_entries_observed_by" FOREIGN KEY ("observed_by_user_id") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" ADD CONSTRAINT "FK_care_observation_tasks_case" FOREIGN KEY ("case_id") REFERENCES "patient_cases"("case_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" ADD CONSTRAINT "FK_care_observation_tasks_template" FOREIGN KEY ("template_id") REFERENCES "care_observation_sheet_templates"("template_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "care_observation_tasks" ADD CONSTRAINT "FK_care_observation_tasks_treatment_order" FOREIGN KEY ("treatment_order_id") REFERENCES "treatment_orders"("treatment_order_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_devices" ADD CONSTRAINT "FK_user_devices_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_education_pod_contents" ADD CONSTRAINT "FK_health_education_pod_contents_operation_type" FOREIGN KEY ("operation_type_id") REFERENCES "operation_types"("operation_type_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_nurse_assignments" ADD CONSTRAINT "FK_room_nurse_assignments_nurse" FOREIGN KEY ("nurse_user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pod_protocol_tracking_logs" ADD CONSTRAINT "FK_pod_tracking_logs_case_id" FOREIGN KEY ("case_id") REFERENCES "patient_cases"("case_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pod_protocol_tracking_logs" ADD CONSTRAINT "FK_pod_tracking_logs_changed_by" FOREIGN KEY ("changed_by") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" ADD CONSTRAINT "FK_assessment_tasks_case" FOREIGN KEY ("case_id") REFERENCES "patient_cases"("case_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessment_tasks" ADD CONSTRAINT "FK_assessment_tasks_assessment" FOREIGN KEY ("assessment_id") REFERENCES "patient_assessments"("assessment_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pod_protocols" ADD CONSTRAINT "FK_d5a013f726d32f46601250c110e" FOREIGN KEY ("operation_type_id") REFERENCES "operation_types"("operation_type_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_engagement_logs" ADD CONSTRAINT "FK_app_engagement_logs_case_id" FOREIGN KEY ("case_id") REFERENCES "patient_cases"("case_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_assessments" ADD CONSTRAINT "FK_patient_assessments_questionnaire_version" FOREIGN KEY ("questionnaire_version_id") REFERENCES "questionnaire_versions"("questionnaire_version_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_questions" ADD CONSTRAINT "FK_survey_questions_questionnaire_version" FOREIGN KEY ("questionnaire_version_id") REFERENCES "questionnaire_versions"("questionnaire_version_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vital_signs" ADD CONSTRAINT "FK_vital_signs_case" FOREIGN KEY ("case_id") REFERENCES "patient_cases"("case_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vital_signs" ADD CONSTRAINT "FK_vital_signs_recorded_by" FOREIGN KEY ("recorded_by_user_id") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_cases" ADD CONSTRAINT "FK_patient_cases_active_treatment_order" FOREIGN KEY ("active_treatment_order_id") REFERENCES "treatment_orders"("treatment_order_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_orders" ADD CONSTRAINT "FK_treatment_orders_case" FOREIGN KEY ("case_id") REFERENCES "patient_cases"("case_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment_orders" ADD CONSTRAINT "FK_treatment_orders_ordered_by" FOREIGN KEY ("ordered_by_user_id") REFERENCES "users"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
