import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Danh mục mã bệnh dùng cho ô "Chẩn đoán" / "Bệnh kèm theo". Dữ liệu mặc định
 * lấy từ Phụ lục "Danh mục mã bệnh theo ICD-10" (Bộ Y tế, 06-byt-kem.pdf),
 * chỉ gồm chương XI — các mã bắt đầu bằng K (bệnh hệ tiêu hóa) — và 2 cột
 * MÃ BỆNH + TÊN BỆNH.
 */
const K_DISEASES: ReadonlyArray<readonly [code: string, name: string]> = [
  ['K00', 'Rối loạn phát triển răng và/hoặc mọc răng'],
  ['K00.0', 'Tật không răng bẩm sinh'],
  ['K00.1', 'Răng thừa'],
  ['K00.2', 'Bất thường kích thước và/hoặc hình dạng răng'],
  ['K00.3', 'Răng đốm màu'],
  ['K00.4', 'Rối loạn tạo răng'],
  ['K00.5', 'Rối loạn di truyền cấu trúc răng, không phân loại mục khác'],
  ['K00.6', 'Rối loạn mọc răng'],
  ['K00.7', 'Hội chứng mọc răng'],
  ['K00.8', 'Rối loạn khác về phát triển răng'],
  ['K00.9', 'Rối loạn phát triển răng, không xác định'],
  ['K01', 'Răng mọc kẹt và/hoặc răng ngầm'],
  ['K01.0', 'Răng ngầm'],
  ['K01.1', 'Răng mọc kẹt'],
  ['K02', 'Sâu răng'],
  ['K02.0', 'Sâu men răng'],
  ['K02.1', 'Sâu ngà răng'],
  ['K02.2', 'Sâu xi măng răng'],
  ['K02.3', 'Sâu răng ngưng tiến triển'],
  ['K02.4', 'Hủy khoáng mô cứng nhiều răng'],
  ['K02.5', 'Sâu răng có hở tủy'],
  ['K02.8', 'Sâu răng khác'],
  ['K02.9', 'Sâu răng, không xác định'],
  ['K03', 'Bệnh mô cứng khác của răng'],
  ['K03.0', 'Mòn răng quá mức'],
  ['K03.1', 'Mòn răng cơ học'],
  ['K03.2', 'Mòn răng hóa học'],
  ['K03.3', 'Tiêu răng bệnh lý'],
  ['K03.4', 'Quá sản xi măng răng'],
  ['K03.5', 'Dính khớp răng'],
  ['K03.6', 'Cao răng'],
  ['K03.7', 'Đổi màu mô cứng sau mọc răng'],
  ['K03.8', 'Bệnh mô cứng xác định khác của răng'],
  ['K03.9', 'Bệnh mô cứng của răng, không xác định'],
  ['K04', 'Bệnh tủy và/hoặc mô quanh chân răng'],
  ['K04.0', 'Viêm tủy răng'],
  ['K04.1', 'Hoại tử tủy răng'],
  ['K04.2', 'Thoái hóa tủy răng'],
  ['K04.3', 'Hình thành mô cứng bất thường trong tủy'],
  ['K04.4', 'Viêm quanh chóp răng cấp tính có nguồn gốc từ tủy răng'],
  ['K04.5', 'Viêm quanh chóp răng mạn tính'],
  ['K04.6', 'Áp xe quanh chóp răng có lỗ rò'],
  ['K04.7', 'Áp xe quanh chóp răng không có lỗ rò'],
  ['K04.8', 'Nang chân răng'],
  ['K04.9', 'Bệnh khác và/hoặc không xác định của tủy và/hoặc mô quanh chóp răng'],
  ['K05', 'Viêm lợi [nướu] và/hoặc bệnh viêm nha chu'],
  ['K05.0', 'Viêm lợi [nướu] cấp tính'],
  ['K05.1', 'Viêm lợi [nướu] mạn tính'],
  ['K05.2', 'Viêm quanh răng [nha chu] cấp tính'],
  ['K05.3', 'Viêm quanh răng [nha chu] mạn tính'],
  ['K05.4', 'Thoái hóa quanh răng [nha chu]'],
  ['K05.5', 'Bệnh quanh răng [nha chu] khác'],
  ['K05.6', 'Bệnh quanh răng [nha chu], không xác định'],
  ['K06', 'Rối loạn khác của lợi [nướu] và/hoặc sống hàm đã mất răng'],
  ['K06.0', 'Tụt lợi [nướu]'],
  ['K06.1', 'Phì đại lợi [nướu]'],
  ['K06.2', 'Tổn thương lợi [nướu] răng và/hoặc sống hàm đã mất răng liên quan chấn thương'],
  ['K06.8', 'Bệnh lý xác định khác của lợi [nướu] và/hoặc sống hàm đã mất răng'],
  ['K06.9', 'Rối loạn ở lợi [nướu] và/hoặc sống hàm đã mất răng, không xác định'],
  ['K07', 'Bất thường hàm mặt [bao gồm khớp cắn lệch]'],
  ['K07.0', 'Bất thường lớn về kích thước xương hàm'],
  ['K07.1', 'Bất thường tương quan sọ mặt'],
  ['K07.2', 'Bất thường tương quan cung răng'],
  ['K07.3', 'Bất thường vị trí răng'],
  ['K07.4', 'Khớp cắn lệch, không xác định'],
  ['K07.5', 'Bất thường chức năng răng mặt'],
  ['K07.6', 'Loạn năng khớp thái dương hàm'],
  ['K07.8', 'Bất thường răng mặt khác'],
  ['K07.9', 'Bất thường răng mặt, không xác định'],
  ['K08', 'Rối loạn khác của răng và/hoặc cấu trúc nâng đỡ'],
  ['K08.0', 'Bong tróc răng do nguyên nhân hệ thống'],
  ['K08.1', 'Mất răng do tai nạn, do nhổ răng hoặc do bệnh nha chu khu trú'],
  ['K08.2', 'Teo sống hàm đã mất răng'],
  ['K08.3', 'Chân răng còn sót'],
  ['K08.8', 'Rối loạn xác định khác của răng và/hoặc cấu trúc nâng đỡ'],
  ['K08.9', 'Rối loạn của răng và/hoặc cấu trúc nâng đỡ, không xác định'],
  ['K09', 'Nang vùng miệng, không phân loại mục khác'],
  ['K09.0', 'Nang nguồn gốc răng'],
  ['K09.1', 'Nang vùng miệng không có nguồn gốc răng'],
  ['K09.2', 'Nang khác của xương hàm'],
  ['K09.8', 'Nang khác ở vùng miệng, không phân loại mục khác'],
  ['K09.9', 'Nang của vùng miệng, không xác định'],
  ['K10', 'Bệnh khác của xương hàm'],
  ['K10.0', 'Rối loạn phát triển của xương hàm'],
  ['K10.1', 'U hạt tế bào khổng lồ, trung tâm'],
  ['K10.2', 'Tình trạng viêm của xương hàm'],
  ['K10.3', 'Viêm ổ răng của xương hàm'],
  ['K10.8', 'Bệnh xác định khác của xương hàm'],
  ['K10.9', 'Bệnh của xương hàm, không xác định'],
  ['K11', 'Bệnh tuyến nước bọt'],
  ['K11.0', 'Teo tuyến nước bọt'],
  ['K11.1', 'Phì đại tuyến nước bọt'],
  ['K11.2', 'Viêm tuyến nước bọt'],
  ['K11.3', 'Áp xe tuyến nước bọt'],
  ['K11.4', 'Lỗ rò tuyến nước bọt'],
  ['K11.5', 'Sỏi tuyến nước bọt'],
  ['K11.6', 'Nang nhầy của tuyến nước bọt'],
  ['K11.7', 'Rối loạn tiết nước bọt'],
  ['K11.8', 'Bệnh khác của tuyến nước bọt'],
  ['K11.9', 'Bệnh của tuyến nước bọt, không xác định'],
  ['K12', 'Viêm miệng và/hoặc tổn thương liên quan'],
  ['K12.0', 'Loét miệng tái phát'],
  ['K12.1', 'Trạng thái khác của viêm miệng'],
  ['K12.2', 'Viêm mô tế bào và/hoặc áp xe của miệng'],
  ['K12.3', 'Viêm niêm mạc miệng (loét)'],
  ['K13', 'Bệnh khác của môi và/hoặc niêm mạc miệng'],
  ['K13.0', 'Bệnh của môi'],
  ['K13.1', 'Tật cắn môi và/hoặc tật cắn má'],
  ['K13.2', 'Bạch sản [mảng trắng] và/hoặc thay đổi của niêm mạc miệng, bao gồm cả lưỡi'],
  ['K13.3', 'Bạch sản dạng tóc ở miệng'],
  ['K13.4', 'U hạt và/hoặc tổn thương dạng u hạt của niêm mạc miệng'],
  ['K13.5', 'Xơ hóa dưới niêm mạc miệng'],
  ['K13.6', 'Tăng sản do kích thích của niêm mạc miệng'],
  ['K13.7', 'Tổn thương khác và/hoặc không xác định của niêm mạc miệng'],
  ['K14', 'Bệnh của lưỡi'],
  ['K14.0', 'Viêm lưỡi'],
  ['K14.1', 'Lưỡi bản đồ'],
  ['K14.2', 'Viêm lưỡi giữa hình trám'],
  ['K14.3', 'Phì đại gai lưỡi'],
  ['K14.4', 'Teo gai lưỡi'],
  ['K14.5', 'Lưỡi nứt'],
  ['K14.6', 'Đau lưỡi'],
  ['K14.8', 'Bệnh khác của lưỡi'],
  ['K14.9', 'Bệnh của lưỡi, không xác định'],
  ['K20', 'Viêm thực quản'],
  ['K21', 'Bệnh trào ngược dạ dày -thực quản'],
  ['K21.0', 'Bệnh trào ngược dạ dày -thực quản kèm viêm thực quản'],
  ['K21.9', 'Bệnh trào ngược dạ dày -thực quản không kèm viêm thực quản'],
  ['K22', 'Bệnh khác của thực quản'],
  ['K22.0', 'Co thắt tâm vị'],
  ['K22.1', 'Loét thực quản'],
  ['K22.2', 'Tắc nghẽn thực quản'],
  ['K22.3', 'Thủng thực quản'],
  ['K22.4', 'Rối loạn vận động thực quản'],
  ['K22.5', 'Túi thừa thực quản, mắc phải'],
  ['K22.6', 'Hội chứng rách - chảy máu dạ dày - thực quản'],
  ['K22.7', 'Thực quản Barrett'],
  ['K22.8', 'Bệnh xác định khác của thực quản'],
  ['K22.9', 'Bệnh của thực quản, không xác định'],
  ['K23', 'Rối loạn thực quản do bệnh phân loại mục khác'],
  ['K23.0', 'Viêm thực quản do lao (A18.8†)'],
  ['K23.1', 'Phình đại thực quản do bệnh Chagas (B57.3†)'],
  ['K23.8', 'Rối loạn thực quản do bệnh khác phân loại mục khác'],
  ['K25', 'Loét dạ dày'],
  ['K25.0', 'Loét dạ dày, cấp tính kèm xuất huyết'],
  ['K25.1', 'Loét dạ dày, cấp tính kèm thủng'],
  ['K25.2', 'Loét dạ dày, cấp tính kèm cả xuất huyết và thủng'],
  ['K25.3', 'Loét dạ dày, cấp tính không xuất huyết hoặc thủng'],
  ['K25.4', 'Loét dạ dày, mạn tính hoặc không xác định kèm xuất huyết'],
  ['K25.5', 'Loét dạ dày, mạn tính hoặc không xác định kèm thủng'],
  ['K25.6', 'Loét dạ dày, mạn tính hoặc không xác định kèm cả xuất huyết và thủng'],
  ['K25.7', 'Loét dạ dày, mạn tính không xuất huyết hoặc thủng'],
  ['K25.9', 'Loét dạ dày, không xác định mạn tính hoặc cấp tính, không xuất huyết hoặc thủng'],
  ['K26', 'Loét tá tràng'],
  ['K26.0', 'Loét tá tràng, cấp tính kèm xuất huyết'],
  ['K26.1', 'Loét tá tràng, cấp tính kèm thủng'],
  ['K26.2', 'Loét tá tràng, cấp tính kèm cả xuất huyết và thủng'],
  ['K26.3', 'Loét tá tràng, cấp tính không xuất huyết hoặc thủng'],
  ['K26.4', 'Loét tá tràng, mạn tính hoặc không xác định kèm xuất huyết'],
  ['K26.5', 'Loét tá tràng, mạn tính hoặc không xác định kèm thủng'],
  ['K26.6', 'Loét tá tràng, mạn tính hoặc không xác định kèm cả xuất huyết và thủng'],
  ['K26.7', 'Loét tá tràng, mạn tính không xuất huyết hoặc thủng'],
  ['K26.9', 'Loét tá tràng, không xác định mạn tính hoặc cấp tính, không xuất huyết hoặc thủng'],
  ['K27', 'Loét dạ dày - tá tràng, vị trí không xác định'],
  ['K27.0', 'Loét dạ dày - tá tràng, vị trí không xác định, cấp tính kèm xuất huyết'],
  ['K27.1', 'Loét dạ dày - tá tràng, vị trí không xác định, cấp tính kèm thủng'],
  ['K27.2', 'Loét dạ dày - tá tràng, vị trí không xác định, cấp tính kèm cả xuất huyết và thủng'],
  ['K27.3', 'Loét dạ dày - tá tràng, vị trí không xác định, cấp tính không xuất huyết hoặc thủng'],
  ['K27.4', 'Loét dạ dày - tá tràng, vị trí không xác định, mạn tính hoặc không xác định kèm xuất huyết'],
  ['K27.5', 'Loét dạ dày - tá tràng, vị trí không xác định, mạn tính hoặc không xác định kèm thủng'],
  ['K27.6', 'Loét dạ dày - tá tràng, vị trí không xác định, mạn tính hoặc không xác định kèm cả xuất huyết và thủng'],
  ['K27.7', 'Loét dạ dày - tá tràng, vị trí không xác định, mạn tính không xuất huyết hoặc thủng'],
  ['K27.9', 'Loét dạ dày - tá tràng, không xác định mạn tính hoặc cấp tính, không xuất huyết hoặc thủng'],
  ['K28', 'Loét dạ dày - hỗng tràng'],
  ['K28.0', 'Loét dạ dày - hỗng tràng, cấp tính kèm xuất huyết'],
  ['K28.1', 'Loét dạ dày - hỗng tràng, cấp tính kèm thủng'],
  ['K28.2', 'Loét dạ dày - hỗng tràng, cấp tính kèm cả xuất huyết và thủng'],
  ['K28.3', 'Loét dạ dày - hỗng tràng, cấp tính không xuất huyết hoặc thủng'],
  ['K28.4', 'Loét dạ dày - hỗng tràng, mạn tính hoặc không xác định kèm xuất huyết'],
  ['K28.5', 'Loét dạ dày - hỗng tràng, mạn tính hoặc không xác định kèm thủng'],
  ['K28.6', 'Loét dạ dày - hỗng tràng, mạn tính hoặc không xác định kèm cả xuất huyết và thủng'],
  ['K28.7', 'Loét dạ dày - hỗng tràng, mạn tính không xuất huyết hoặc thủng'],
  ['K28.9', 'Loét dạ dày - hỗng tràng, không xác định mạn tính hoặc cấp tính, không xuất huyết hoặc thủng'],
  ['K29', 'Viêm dạ dày và/hoặc tá tràng'],
  ['K29.0', 'Viêm dạ dày xuất huyết cấp tính'],
  ['K29.1', 'Viêm dạ dày cấp tính khác'],
  ['K29.2', 'Viêm dạ dày do rượu'],
  ['K29.3', 'Viêm nông niêm mạc dạ dày mạn tính'],
  ['K29.4', 'Viêm teo niêm mạc dạ dày mạn tính'],
  ['K29.5', 'Viêm dạ dày mạn tính, không xác định'],
  ['K29.6', 'Viêm dạ dày khác'],
  ['K29.7', 'Viêm dạ dày, không xác định'],
  ['K29.8', 'Viêm tá tràng'],
  ['K29.9', 'Viêm dạ dày tá tràng, không xác định'],
  ['K30', 'Rối loạn tiêu hóa chức năng [không do loét]'],
  ['K31', 'Bệnh khác của dạ dày và/hoặc tá tràng'],
  ['K31.0', 'Giãn dạ dày cấp tính'],
  ['K31.1', 'Hẹp môn vị do phì đại ở người lớn'],
  ['K31.2', 'Hẹp và/hoặc co hẹp dạ dày dạng đồng hồ cát'],
  ['K31.3', 'Co thắt môn vị, không phân loại mục khác'],
  ['K31.4', 'Túi thừa dạ dày'],
  ['K31.5', 'Tắc tá tràng'],
  ['K31.6', 'Rò dạ dày và/hoặc tá tràng'],
  ['K31.7', 'Polyp dạ dày và/hoặc tá tràng'],
  ['K31.8', 'Bệnh xác định khác của dạ dày và/hoặc tá tràng'],
  ['K31.9', 'Bệnh không xác định của dạ dày và/hoặc tá tràng'],
  ['K35', 'Viêm ruột thừa cấp tính'],
  ['K35.2', 'Viêm ruột thừa cấp tính kèm viêm phúc mạc toàn bộ'],
  ['K35.3', 'Viêm ruột thừa cấp tính kèm viêm phúc mạc khu trú'],
  ['K35.8', 'Viêm ruột thừa cấp tính, khác và/hoặc không xác định'],
  ['K36', 'Viêm ruột thừa khác'],
  ['K37', 'Viêm ruột thừa không xác định'],
  ['K38', 'Bệnh khác của ruột thừa'],
  ['K38.0', 'Tăng sản ruột thừa'],
  ['K38.1', 'Kết sỏi ở ruột thừa'],
  ['K38.2', 'Túi thừa của ruột thừa'],
  ['K38.3', 'Rò ruột thừa'],
  ['K38.8', 'Bệnh xác định khác của ruột thừa'],
  ['K38.9', 'Bệnh không xác định của ruột thừa'],
  ['K40', 'Thoát vị bẹn'],
  ['K40.0', 'Thoát vị bẹn hai bên, kèm tắc nghẽn, không hoại thư'],
  ['K40.1', 'Thoát vị bẹn hai bên, kèm hoại thư'],
  ['K40.2', 'Thoát vị bẹn hai bên, không tắc nghẽn hoặc hoại thư'],
  ['K40.3', 'Thoát vị bẹn một bên hoặc không xác định, kèm tắc nghẽn, không hoại thư'],
  ['K40.4', 'Thoát vị bẹn một bên hoặc không xác định, kèm hoại thư'],
  ['K40.9', 'Thoát vị bẹn một bên hoặc không xác định, không tắc nghẽn hoặc hoại thư'],
  ['K41', 'Thoát vị đùi'],
  ['K41.0', 'Thoát vị đùi hai bên, kèm tắc nghẽn, không hoại thư'],
  ['K41.1', 'Thoát vị đùi hai bên, kèm hoại thư'],
  ['K41.2', 'Thoát vị đùi hai bên, không tắc nghẽn hoặc hoại thư'],
  ['K41.3', 'Thoát vị đùi một bên hoặc không xác định, kèm tắc nghẽn, không hoại thư'],
  ['K41.4', 'Thoát vị đùi một bên hoặc không xác định, kèm hoại thư'],
  ['K41.9', 'Thoát vị đùi một bên hoặc không xác định, không tắc nghẽn hoặc hoại thư'],
  ['K42', 'Thoát vị rốn'],
  ['K42.0', 'Thoát vị rốn kèm tắc nghẽn, không hoại thư'],
  ['K42.1', 'Thoát vị rốn kèm hoại thư'],
  ['K42.9', 'Thoát vị rốn không tắc nghẽn hoặc hoại thư'],
  ['K43', 'Thoát vị thành bụng'],
  ['K43.0', 'Thoát vị qua vết mổ kèm tắc nghẽn, không hoại thư'],
  ['K43.1', 'Thoát vị qua vết mổ kèm hoại thư'],
  ['K43.2', 'Thoát vị qua vết mổ không tắc nghẽn hoặc hoại thư'],
  ['K43.3', 'Thoát vị quanh lỗ mở thông ruột, đường tiết niệu ra da kèm tắc nghẽn, không hoại thư'],
  ['K43.4', 'Thoát vị quanh lỗ mở thông ruột, đường tiết niệu ra da kèm hoại thư'],
  ['K43.5', 'Thoát vị quanh lỗ mở thông ruột, đường tiết niệu ra da không tắc nghẽn hoặc hoại thư'],
  ['K43.6', 'Thoát vị thành bụng khác và/hoặc không xác định kèm tắc nghẽn, không hoại thư'],
  ['K43.7', 'Thoát vị thành bụng khác và/hoặc không xác định kèm hoại thư'],
  ['K43.9', 'Thoát vị thành bụng khác và/hoặc không xác định không tắc nghẽn hoặc hoại thư'],
  ['K44', 'Thoát vị cơ hoành'],
  ['K44.0', 'Thoát vị cơ hoành kèm tắc nghẽn, không hoại thư'],
  ['K44.1', 'Thoát vị cơ hoành kèm hoại thư'],
  ['K44.9', 'Thoát vị cơ hoành, không tắc nghẽn hoặc hoại thư'],
  ['K45', 'Thoát vị bụng khác'],
  ['K45.0', 'Thoát vị bụng xác định khác có tắc nghẽn, không hoại thư'],
  ['K45.1', 'Thoát vị bụng xác định khác, có hoại thư'],
  ['K45.8', 'Thoát vị bụng xác định khác, không tắc nghẽn hoặc hoại thư'],
  ['K46', 'Thoát vị bụng không xác định'],
  ['K46.0', 'Thoát vị bụng không xác định có tắc nghẽn, không hoại thư'],
  ['K46.1', 'Thoát vị bụng không xác định, có hoại thư'],
  ['K46.9', 'Thoát vị bụng không xác định, không tắc nghẽn hoặc hoại thư'],
  ['K50', 'Bệnh Crohn [viêm ruột từng vùng]'],
  ['K50.0', 'Bệnh Crohn của ruột non'],
  ['K50.1', 'Bệnh Crohn của đại tràng'],
  ['K50.8', 'Bệnh Crohn khác'],
  ['K50.9', 'Bệnh Crohn, không xác định'],
  ['K51', 'Viêm loét đại tràng'],
  ['K51.0', 'Viêm loét toàn ruột (mạn tính)'],
  ['K51.2', 'Viêm loét trực tràng (mạn tính)'],
  ['K51.3', 'Viêm loét đại tràng sigma (mạn tính)'],
  ['K51.4', 'Nhiều polyp viêm'],
  ['K51.5', 'Viêm loét đại tràng trái'],
  ['K51.8', 'Viêm loét khác của đại tràng'],
  ['K51.9', 'Viêm loét không xác định của đại tràng'],
  ['K52', 'Viêm dạ dày - ruột và/hoặc viêm đại tràng khác không do nhiễm trùng'],
  ['K52.0', 'Viêm dạ dày - ruột và/hoặc đại tràng do xạ trị'],
  ['K52.1', 'Viêm dạ dày - ruột và/hoặc đại tràng do nhiễm độc'],
  ['K52.2', 'Viêm dạ dày - ruột và/hoặc đại tràng do dị ứng và/hoặc do chế độ ăn'],
  ['K52.3', 'Viêm đại tràng không xác định'],
  ['K52.8', 'Viêm dạ dày - ruột và/hoặc đại tràng xác định khác không do nhiễm trùng'],
  ['K52.9', 'Viêm dạ dày - ruột và/hoặc viêm đại tràng không do nhiễm trùng, không xác định'],
  ['K55', 'Rối loạn của mạch máu ruột'],
  ['K55.0', 'Rối loạn mạch máu ruột cấp tính'],
  ['K55.1', 'Rối loạn mạch máu ruột mạn tính'],
  ['K55.2', 'Loạn sản mạch máu của đại tràng'],
  ['K55.3', 'Loạn sản mạch máu của ruột non'],
  ['K55.8', 'Rối loạn khác của mạch máu ruột'],
  ['K55.9', 'Rối loạn của mạch máu ruột, không xác định'],
  ['K56', 'Liệt ruột và/hoặc tắc nghẽn ruột không có thoát vị'],
  ['K56.0', 'Liệt ruột'],
  ['K56.1', 'Lồng ruột'],
  ['K56.2', 'Xoắn ruột'],
  ['K56.3', 'Tắc ruột do sỏi'],
  ['K56.4', 'Nghẹt ruột khác'],
  ['K56.5', 'Dính ruột [thành dải] có tắc nghẽn'],
  ['K56.6', 'Tắc nghẽn ruột khác và/hoặc không xác định'],
  ['K56.7', 'Tắc ruột, không xác định'],
  ['K57', 'Bệnh túi thừa của ruột'],
  ['K57.0', 'Bệnh túi thừa của ruột non, có thủng và/hoặc áp xe'],
  ['K57.1', 'Bệnh túi thừa của ruột non, không thủng hoặc áp xe'],
  ['K57.2', 'Bệnh túi thừa của đại tràng có thủng và/hoặc áp xe'],
  ['K57.3', 'Bệnh túi thừa của đại tràng không thủng hoặc áp xe'],
  ['K57.4', 'Bệnh túi thừa của cả ruột non và đại tràng có thủng và/hoặc áp xe'],
  ['K57.5', 'Bệnh túi thừa của cả ruột non và đại tràng không thủng hoặc áp xe'],
  ['K57.8', 'Bệnh túi thừa của ruột, phần không xác định, kèm thủng và áp xe'],
  ['K57.9', 'Bệnh túi thừa của ruột, phần không xác định, không thủng hoặc áp xe'],
  ['K58', 'Hội chứng ruột kích thích'],
  ['K58.1', 'Hội chứng ruột kích thích thể tiêu chảy (IBS-D)'],
  ['K58.2', 'Hội chứng ruột kích thích thể táo bón (IBS-C)'],
  ['K58.3', 'Hội chứng ruột kích thích hỗn hợp (IBS-M)'],
  ['K58.8', 'Hội chứng khác và/hoặc không xác định của ruột kích thích'],
  ['K59', 'Rối loạn chức năng khác của ruột'],
  ['K59.0', 'Táo bón'],
  ['K59.1', 'Tiêu chảy chức năng'],
  ['K59.2', 'Rối loạn ruột do nguyên nhân thần kinh, không phân loại mục khác'],
  ['K59.3', 'Phình đại tràng, không phân loại mục khác'],
  ['K59.4', 'Co thắt hậu môn'],
  ['K59.8', 'Rối loạn chức năng xác định khác của ruột'],
  ['K59.9', 'Rối loạn chức năng của ruột, không xác định'],
  ['K60', 'Nứt kẽ và/hoặc rò vùng hậu môn và/hoặc trực tràng'],
  ['K60.0', 'Nứt kẽ hậu môn cấp tính'],
  ['K60.1', 'Nứt kẽ hậu môn mạn tính'],
  ['K60.2', 'Nứt ống hậu môn, không xác định'],
  ['K60.3', 'Rò hậu môn'],
  ['K60.4', 'Rò trực tràng'],
  ['K60.5', 'Rò hậu môn trực tràng'],
  ['K61', 'Áp xe vùng hậu môn và/hoặc trực tràng'],
  ['K61.0', 'Áp xe hậu môn'],
  ['K61.1', 'Áp xe trực tràng'],
  ['K61.2', 'Áp xe hậu môn trực tràng'],
  ['K61.3', 'Áp xe ụ ngồi - trực tràng'],
  ['K61.4', 'Áp xe trong cơ thắt hậu môn'],
  ['K62', 'Bệnh khác của hậu môn và/hoặc trực tràng'],
  ['K62.0', 'Polyp hậu môn'],
  ['K62.1', 'Polyp trực tràng'],
  ['K62.2', 'Sa hậu môn'],
  ['K62.3', 'Sa trực tràng qua hậu môn [toàn bộ]'],
  ['K62.4', 'Hẹp trực tràng và/hoặc ống hậu môn'],
  ['K62.5', 'Xuất huyết hậu môn và/hoặc trực tràng'],
  ['K62.6', 'Loét hậu môn và/hoặc trực tràng'],
  ['K62.7', 'Viêm trực tràng do xạ trị'],
  ['K62.8', 'Bệnh xác định khác của hậu môn và/hoặc trực tràng'],
  ['K62.9', 'Bệnh của hậu môn và/hoặc trực tràng, không xác định'],
  ['K63', 'Bệnh khác của ruột'],
  ['K63.0', 'Áp xe ruột'],
  ['K63.1', 'Thủng ruột (không do chấn thương)'],
  ['K63.2', 'Rò ruột'],
  ['K63.3', 'Loét ruột'],
  ['K63.4', 'Sa ruột'],
  ['K63.5', 'Polyp đại tràng'],
  ['K63.8', 'Bệnh xác định khác của ruột'],
  ['K63.9', 'Bệnh của ruột, không xác định'],
  ['K64', 'Bệnh trĩ và/hoặc huyết khối tĩnh mạch quanh hậu môn'],
  ['K64.0', 'Bệnh trĩ độ I'],
  ['K64.1', 'Bệnh trĩ độ II'],
  ['K64.2', 'Bệnh trĩ độ III'],
  ['K64.3', 'Bệnh trĩ độ IV'],
  ['K64.4', 'Vạt da thừa còn sót lại của bệnh trĩ'],
  ['K64.5', 'Huyết khối tĩnh mạch quanh hậu môn'],
  ['K64.8', 'Bệnh trĩ xác định khác'],
  ['K64.9', 'Bệnh trĩ, không xác định'],
  ['K65', 'Viêm phúc mạc'],
  ['K65.0', 'Viêm phúc mạc cấp tính'],
  ['K65.8', 'Viêm phúc mạc khác'],
  ['K65.9', 'Viêm phúc mạc, không xác định'],
  ['K66', 'Rối loạn khác của phúc mạc'],
  ['K66.0', 'Dính phúc mạc'],
  ['K66.1', 'Tràn máu phúc mạc'],
  ['K66.2', 'Xơ hóa vùng sau phúc mạc'],
  ['K66.8', 'Rối loạn xác định khác của phúc mạc'],
  ['K66.9', 'Rối loạn của phúc mạc, không xác định'],
  ['K67', 'Rối loạn của phúc mạc do bệnh nhiễm trùng phân loại mục khác'],
  ['K67.0', 'Viêm phúc mạc do nhiễm chlamydia (A74.8†)'],
  ['K67.1', 'Viêm phúc mạc do bệnh lậu cầu khuẩn (A54.8†)'],
  ['K67.2', 'Viêm phúc mạc do bệnh giang mai (A52.7†)'],
  ['K67.3', 'Viêm phúc mạc do bệnh lao (A18.3†)'],
  ['K67.8', 'Rối loạn khác của phúc mạc do bệnh nhiễm trùng phân loại mục khác'],
  ['K70', 'Bệnh gan do rượu'],
  ['K70.0', 'Gan nhiễm mỡ do rượu'],
  ['K70.1', 'Viêm gan do rượu'],
  ['K70.2', 'Bệnh xơ gan và/hoặc xơ hóa gan do rượu'],
  ['K70.3', 'Xơ gan do rượu'],
  ['K70.4', 'Suy gan do rượu'],
  ['K70.9', 'Bệnh gan do rượu, không xác định'],
  ['K71', 'Bệnh gan nhiễm độc'],
  ['K71.0', 'Bệnh gan nhiễm độc kèm ứ mật'],
  ['K71.1', 'Bệnh gan nhiễm độc kèm hoại tử gan'],
  ['K71.2', 'Bệnh gan nhiễm độc kèm viêm gan cấp tính'],
  ['K71.3', 'Bệnh gan nhiễm độc kèm viêm gan mạn tính dai dẳng'],
  ['K71.4', 'Bệnh gan nhiễm độc kèm viêm tiểu thùy gan mạn tính'],
  ['K71.5', 'Bệnh gan nhiễm độc kèm viêm gan mạn tính hoạt động'],
  ['K71.6', 'Bệnh gan nhiễm độc kèm viêm gan, không phân loại mục khác'],
  ['K71.7', 'Bệnh gan nhiễm độc kèm xơ hóa gan và/hoặc xơ gan'],
  ['K71.8', 'Bệnh gan nhiễm độc kèm rối loạn khác của gan'],
  ['K71.9', 'Bệnh gan nhiễm độc, không xác định'],
  ['K72', 'Suy gan, không phân loại mục khác'],
  ['K72.0', 'Suy gan cấp tính và/hoặc bán cấp tính'],
  ['K72.1', 'Suy gan mạn tính'],
  ['K72.9', 'Suy gan, không xác định'],
  ['K73', 'Viêm gan mạn tính, không phân loại mục khác'],
  ['K73.0', 'Viêm gan mạn tính dai dẳng, không phân loại mục khác'],
  ['K73.1', 'Viêm tiểu thùy gan mạn, không phân loại mục khác'],
  ['K73.2', 'Viêm gan mạn tính hoạt động, không phân loại mục khác'],
  ['K73.8', 'Viêm gan mạn tính khác, không phân loại mục khác'],
  ['K73.9', 'Viêm gan mạn tính, không xác định'],
  ['K74', 'Xơ hóa gan và/hoặc xơ gan'],
  ['K74.0', 'Xơ hóa gan'],
  ['K74.1', 'Xơ cứng gan'],
  ['K74.2', 'Gan xơ hóa với gan xơ cứng'],
  ['K74.3', 'Xơ gan mật nguyên phát'],
  ['K74.4', 'Xơ gan mật thứ phát'],
  ['K74.5', 'Xơ gan mật, không xác định'],
  ['K74.6', 'Xơ gan khác và/hoặc không xác định'],
  ['K75', 'Bệnh viêm gan khác'],
  ['K75.0', 'Áp xe gan'],
  ['K75.1', 'Viêm tĩnh mạch cửa'],
  ['K75.2', 'Viêm gan phản ứng, không xác định cụ thể'],
  ['K75.3', 'Viêm gan dạng u hạt, không phân loại mục khác'],
  ['K75.4', 'Viêm gan tự miễn'],
  ['K75.8', 'Bệnh viêm gan xác định khác'],
  ['K75.9', 'Bệnh viêm gan, không xác định'],
  ['K76', 'Bệnh gan khác'],
  ['K76.0', 'Gan (biến đổi của gan) nhiễm mỡ, không phân loại mục khác'],
  ['K76.1', 'Xung huyết thụ động mạn tính ở gan'],
  ['K76.2', 'Hoại tử xuất huyết vùng trung tâm của gan'],
  ['K76.3', 'Nhồi máu gan'],
  ['K76.4', 'Rối loạn mạch máu trong gan'],
  ['K76.5', 'Bệnh tắc tĩnh mạch trên gan'],
  ['K76.6', 'Tăng áp lực tĩnh mạch cửa'],
  ['K76.7', 'Hội chứng gan - thận'],
  ['K76.8', 'Bệnh xác định khác của gan'],
  ['K76.9', 'Bệnh của gan, không xác định'],
  ['K77', 'Rối loạn gan do bệnh phân loại mục khác'],
  ['K77.0', 'Rối loạn gan do bệnh nhiễm trùng và/hoặc ký sinh trùng phân loại mục khác'],
  ['K77.8', 'Rối loạn gan do bệnh khác phân loại mục khác'],
  ['K80', 'Bệnh sỏi mật'],
  ['K80.0', 'Sỏi túi mật kèm viêm túi mật cấp tính'],
  ['K80.1', 'Sỏi túi mật kèm viêm túi mật khác'],
  ['K80.2', 'Sỏi túi mật không kèm viêm túi mật'],
  ['K80.3', 'Sỏi ống mật kèm viêm đường dẫn mật'],
  ['K80.4', 'Sỏi đường mật kèm viêm túi mật'],
  ['K80.5', 'Sỏi mật không viêm đường dẫn mật hay viêm túi mật'],
  ['K80.8', 'Sỏi mật khác'],
  ['K81', 'Viêm túi mật'],
  ['K81.0', 'Viêm túi mật cấp tính'],
  ['K81.1', 'Viêm túi mật mạn tính'],
  ['K81.8', 'Viêm túi mật thể khác'],
  ['K81.9', 'Viêm túi mật, không xác định'],
  ['K82', 'Bệnh khác của túi mật'],
  ['K82.0', 'Tắc nghẽn túi mật'],
  ['K82.1', 'Tràn dịch túi mật'],
  ['K82.2', 'Thủng túi mật'],
  ['K82.3', 'Rò túi mật'],
  ['K82.4', 'Tích tụ cholesterol ở túi mật'],
  ['K82.8', 'Bệnh xác định khác của túi mật'],
  ['K82.9', 'Bệnh của túi mật, không xác định'],
  ['K83', 'Bệnh khác của đường mật'],
  ['K83.0', 'Viêm đường mật'],
  ['K83.1', 'Tắc nghẽn ống mật'],
  ['K83.2', 'Thủng đường mật'],
  ['K83.3', 'Rò đường mật'],
  ['K83.4', 'Co thắt cơ vòng Oddi'],
  ['K83.5', 'U nang đường mật'],
  ['K83.8', 'Bệnh xác định khác của đường mật'],
  ['K83.9', 'Bệnh đường mật, không xác định'],
  ['K85', 'Viêm tụy cấp tính'],
  ['K85.0', 'Viêm tụy cấp tính vô căn'],
  ['K85.1', 'Viêm tụy cấp tính do mật'],
  ['K85.2', 'Viêm tụy cấp tính do rượu'],
  ['K85.3', 'Viêm tụy cấp tính do thuốc'],
  ['K85.8', 'Viêm tụy cấp tính khác'],
  ['K85.9', 'Viêm tụy cấp tính, không xác định'],
  ['K86', 'Bệnh khác của tụy'],
  ['K86.0', 'Viêm tụy mạn tính do rượu'],
  ['K86.1', 'Viêm tụy mạn tính thể khác'],
  ['K86.2', 'U nang của tụy'],
  ['K86.3', 'U nang giả của tụy'],
  ['K86.8', 'Bệnh xác định khác của tụy'],
  ['K86.9', 'Bệnh của tụy, không xác định'],
  ['K87', 'Rối loạn của túi mật, đường mật và/hoặc tụy do bệnh phân loại mục khác'],
  ['K87.0', 'Rối loạn của túi mật và/hoặc đường mật do bệnh phân loại mục khác'],
  ['K87.1', 'Rối loạn của tụy do bệnh phân loại mục khác'],
  ['K90', 'Suy giảm hấp thu ở ruột'],
  ['K90.0', 'Bệnh Coeliac'],
  ['K90.1', 'Bệnh tiêu chảy nhiệt đới'],
  ['K90.2', 'Hội chứng quai ruột, không phân loại mục khác'],
  ['K90.3', 'Tiêu chảy phân mỡ [suy giảm hấp thu chất béo] do tụy'],
  ['K90.4', 'Suy giảm hấp thu do không dung nạp, không phân loại mục khác'],
  ['K90.8', 'Suy giảm hấp thu khác ở ruột'],
  ['K90.9', 'Suy giảm hấp thu ở ruột, không xác định'],
  ['K91', 'Rối loạn của hệ tiêu hóa sau can thiệp, không phân loại mục khác'],
  ['K91.0', 'Nôn sau phẫu thuật đường tiêu hóa'],
  ['K91.1', 'Hội chứng sau phẫu thuật dạ dày'],
  ['K91.2', 'Suy giảm hấp thu sau phẫu thuật, không phân loại mục khác'],
  ['K91.3', 'Tắc nghẽn ruột sau mổ'],
  ['K91.4', 'Suy chức năng sau mở thông đại tràng và/hoặc mở thông ruột non ra da'],
  ['K91.5', 'Hội chứng sau cắt túi mật'],
  ['K91.8', 'Rối loạn khác của hệ tiêu hóa sau can thiệp, không phân loại mục khác'],
  ['K91.9', 'Rối loạn của hệ tiêu hóa sau can thiệp, không xác định'],
  ['K92', 'Bệnh khác của hệ tiêu hóa'],
  ['K92.0', 'Nôn ra máu [thổ huyết]'],
  ['K92.1', 'Đi ngoài phân đen'],
  ['K92.2', 'Xuất huyết tiêu hóa [phân đen], không xác định'],
  ['K92.8', 'Bệnh xác định khác của hệ tiêu hóa'],
  ['K92.9', 'Bệnh của hệ tiêu hóa, không xác định'],
  ['K93', 'Rối loạn của cơ quan tiêu hóa khác do bệnh phân loại mục khác'],
  ['K93.0', 'Rối loạn ở ruột, phúc mạc và/hoặc tuyến mạc treo do bệnh lao (A18.3†)'],
  ['K93.1', 'Phình đại tràng do bệnh Chagas (B57.3†)'],
  ['K93.8', 'Rối loạn cơ quan tiêu hóa xác định khác do bệnh phân loại mục khác'],
];

/** Lowercase, bỏ dấu tiếng Việt — để tìm "viem da day" vẫn ra "Viêm dạ dày". */
function toSearchText(code: string, name: string): string {
  return `${code} ${name}`
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/đ/g, 'd')
    .replace(/Đ/g, 'D')
    .toLowerCase();
}

export class CreateDiseasesTable1790200000000 implements MigrationInterface {
  name = 'CreateDiseasesTable1790200000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const schemaName = process.env.DB_SCHEMA ?? 'public';
    const schema = `"${schemaName}"`;

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS ${schema}."diseases" (
        "code" VARCHAR(10) PRIMARY KEY,
        "name" TEXT NOT NULL,
        "search_text" TEXT NOT NULL
      )
    `);

    const params: string[] = [];
    const values = K_DISEASES.map(([code, name], i) => {
      params.push(code, name, toSearchText(code, name));
      return `($${i * 3 + 1}, $${i * 3 + 2}, $${i * 3 + 3})`;
    });

    await queryRunner.query(
      `INSERT INTO ${schema}."diseases" ("code", "name", "search_text")
       VALUES ${values.join(', ')}
       ON CONFLICT ("code") DO NOTHING`,
      params,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const schemaName = process.env.DB_SCHEMA ?? 'public';
    const schema = `"${schemaName}"`;

    await queryRunner.query(`DROP TABLE IF EXISTS ${schema}."diseases"`);
  }
}
