import { MigrationInterface, QueryRunner } from "typeorm";

export class InitDB1779179339746 implements MigrationInterface {
    name = 'InitDB1779179339746'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallet_transactions" DROP CONSTRAINT "wallet_transactions_wallet_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."accounts" DROP CONSTRAINT "fk_accounts_user"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."booking_seats" DROP CONSTRAINT "booking_seats_booking_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."seat_templates" DROP CONSTRAINT "seat_templates_vehicle_type_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicles" DROP CONSTRAINT "vehicles_driver_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicles" DROP CONSTRAINT "vehicles_type_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."driver_profiles" DROP CONSTRAINT "driver_profiles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" DROP CONSTRAINT "trips_driver_profile_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" DROP CONSTRAINT "trips_vehicle_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" DROP CONSTRAINT "trips_start_hub_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" DROP CONSTRAINT "trips_end_hub_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."bookings" DROP CONSTRAINT "bookings_trip_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."bookings" DROP CONSTRAINT "bookings_passenger_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."users" DROP CONSTRAINT "users_account_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallets" DROP CONSTRAINT "wallets_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallet_transactions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallet_transactions" ALTER COLUMN "last_modified_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."accounts" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."accounts" ALTER COLUMN "last_modified_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."accounts" ADD CONSTRAINT "UQ_3000dad1da61b29953f07476324" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."booking_seats" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."booking_seats" ALTER COLUMN "last_modified_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."seat_templates" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."seat_templates" ALTER COLUMN "last_modified_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicle_types" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicle_types" ALTER COLUMN "last_modified_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicles" ALTER COLUMN "last_modified_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."driver_profiles" ALTER COLUMN "total_trips" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."driver_profiles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."driver_profiles" ALTER COLUMN "last_modified_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."hubs" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."hubs" ALTER COLUMN "last_modified_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" ALTER COLUMN "last_modified_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."bookings" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."bookings" ALTER COLUMN "last_modified_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."users" ALTER COLUMN "last_modified_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."users" ADD CONSTRAINT "UQ_17a709b8b6146c491e6615c29d7" UNIQUE ("account_id")`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallets" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallets" ALTER COLUMN "last_modified_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "wallet_transactions_pkey" ON "SEP490_G57"."wallet_transactions" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "accounts_pkey" ON "SEP490_G57"."accounts" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "accounts_firebase_uid_key" ON "SEP490_G57"."accounts" ("firebase_uid") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "accounts_email_key" ON "SEP490_G57"."accounts" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "booking_seats_pkey" ON "SEP490_G57"."booking_seats" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "seat_templates_pkey" ON "SEP490_G57"."seat_templates" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "vehicle_types_pkey" ON "SEP490_G57"."vehicle_types" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "vehicles_pkey" ON "SEP490_G57"."vehicles" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "driver_profiles_pkey" ON "SEP490_G57"."driver_profiles" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "hubs_pkey" ON "SEP490_G57"."hubs" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "trips_pkey" ON "SEP490_G57"."trips" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "bookings_pkey" ON "SEP490_G57"."bookings" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_pkey" ON "SEP490_G57"."users" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "wallets_pkey" ON "SEP490_G57"."wallets" ("id") `);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallet_transactions" ADD CONSTRAINT "FK_c57d19129968160f4db28fc8b28" FOREIGN KEY ("wallet_id") REFERENCES "SEP490_G57"."wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."accounts" ADD CONSTRAINT "FK_3000dad1da61b29953f07476324" FOREIGN KEY ("user_id") REFERENCES "SEP490_G57"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."booking_seats" ADD CONSTRAINT "FK_25c8b5c1e010af1cd2f699c5926" FOREIGN KEY ("booking_id") REFERENCES "SEP490_G57"."bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."seat_templates" ADD CONSTRAINT "FK_4e4e59b33686a70ad5c55d2fd84" FOREIGN KEY ("vehicle_type_id") REFERENCES "SEP490_G57"."vehicle_types"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicles" ADD CONSTRAINT "FK_9c2e0a8772c9e43b32f57bfcfcc" FOREIGN KEY ("driver_id") REFERENCES "SEP490_G57"."driver_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicles" ADD CONSTRAINT "FK_218aae238bdeffb5b71b8c82c02" FOREIGN KEY ("type_id") REFERENCES "SEP490_G57"."vehicle_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."driver_profiles" ADD CONSTRAINT "FK_cec43742cd6dea0e8fcae3e29d8" FOREIGN KEY ("user_id") REFERENCES "SEP490_G57"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" ADD CONSTRAINT "FK_022d2f367f5771b453a4f6c4de5" FOREIGN KEY ("driver_profile_id") REFERENCES "SEP490_G57"."driver_profiles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" ADD CONSTRAINT "FK_c6556dc20de0d99c653f88b9a27" FOREIGN KEY ("end_hub_id") REFERENCES "SEP490_G57"."hubs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" ADD CONSTRAINT "FK_6fe34389993f90753c4c9c9a2a2" FOREIGN KEY ("start_hub_id") REFERENCES "SEP490_G57"."hubs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" ADD CONSTRAINT "FK_ab4b806373c2ee43946679d572e" FOREIGN KEY ("vehicle_id") REFERENCES "SEP490_G57"."vehicles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."bookings" ADD CONSTRAINT "FK_1a764d454e20296cfa277d8742e" FOREIGN KEY ("passenger_id") REFERENCES "SEP490_G57"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."bookings" ADD CONSTRAINT "FK_45fa98a28a6944e39d8a5754bd1" FOREIGN KEY ("trip_id") REFERENCES "SEP490_G57"."trips"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."users" ADD CONSTRAINT "FK_17a709b8b6146c491e6615c29d7" FOREIGN KEY ("account_id") REFERENCES "SEP490_G57"."accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallets" ADD CONSTRAINT "FK_92558c08091598f7a4439586cda" FOREIGN KEY ("user_id") REFERENCES "SEP490_G57"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallets" DROP CONSTRAINT "FK_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."users" DROP CONSTRAINT "FK_17a709b8b6146c491e6615c29d7"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."bookings" DROP CONSTRAINT "FK_45fa98a28a6944e39d8a5754bd1"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."bookings" DROP CONSTRAINT "FK_1a764d454e20296cfa277d8742e"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" DROP CONSTRAINT "FK_ab4b806373c2ee43946679d572e"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" DROP CONSTRAINT "FK_6fe34389993f90753c4c9c9a2a2"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" DROP CONSTRAINT "FK_c6556dc20de0d99c653f88b9a27"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" DROP CONSTRAINT "FK_022d2f367f5771b453a4f6c4de5"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."driver_profiles" DROP CONSTRAINT "FK_cec43742cd6dea0e8fcae3e29d8"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicles" DROP CONSTRAINT "FK_218aae238bdeffb5b71b8c82c02"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicles" DROP CONSTRAINT "FK_9c2e0a8772c9e43b32f57bfcfcc"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."seat_templates" DROP CONSTRAINT "FK_4e4e59b33686a70ad5c55d2fd84"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."booking_seats" DROP CONSTRAINT "FK_25c8b5c1e010af1cd2f699c5926"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."accounts" DROP CONSTRAINT "FK_3000dad1da61b29953f07476324"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallet_transactions" DROP CONSTRAINT "FK_c57d19129968160f4db28fc8b28"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."wallets_pkey"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."users_pkey"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."bookings_pkey"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."trips_pkey"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."hubs_pkey"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."driver_profiles_pkey"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."vehicles_pkey"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."vehicle_types_pkey"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."seat_templates_pkey"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."booking_seats_pkey"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."accounts_email_key"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."accounts_firebase_uid_key"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."accounts_pkey"`);
        await queryRunner.query(`DROP INDEX "SEP490_G57"."wallet_transactions_pkey"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallets" ALTER COLUMN "last_modified_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallets" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."users" DROP CONSTRAINT "UQ_17a709b8b6146c491e6615c29d7"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."users" ALTER COLUMN "last_modified_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."bookings" ALTER COLUMN "last_modified_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."bookings" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" ALTER COLUMN "last_modified_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."hubs" ALTER COLUMN "last_modified_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."hubs" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."driver_profiles" ALTER COLUMN "last_modified_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."driver_profiles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."driver_profiles" ALTER COLUMN "total_trips" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicles" ALTER COLUMN "last_modified_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicle_types" ALTER COLUMN "last_modified_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicle_types" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."seat_templates" ALTER COLUMN "last_modified_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."seat_templates" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."booking_seats" ALTER COLUMN "last_modified_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."booking_seats" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."accounts" DROP CONSTRAINT "UQ_3000dad1da61b29953f07476324"`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."accounts" ALTER COLUMN "last_modified_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."accounts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallet_transactions" ALTER COLUMN "last_modified_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallet_transactions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallets" ADD CONSTRAINT "wallets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "SEP490_G57"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."users" ADD CONSTRAINT "users_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "SEP490_G57"."accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."bookings" ADD CONSTRAINT "bookings_passenger_id_fkey" FOREIGN KEY ("passenger_id") REFERENCES "SEP490_G57"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."bookings" ADD CONSTRAINT "bookings_trip_id_fkey" FOREIGN KEY ("trip_id") REFERENCES "SEP490_G57"."trips"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" ADD CONSTRAINT "trips_end_hub_id_fkey" FOREIGN KEY ("end_hub_id") REFERENCES "SEP490_G57"."hubs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" ADD CONSTRAINT "trips_start_hub_id_fkey" FOREIGN KEY ("start_hub_id") REFERENCES "SEP490_G57"."hubs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" ADD CONSTRAINT "trips_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "SEP490_G57"."vehicles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."trips" ADD CONSTRAINT "trips_driver_profile_id_fkey" FOREIGN KEY ("driver_profile_id") REFERENCES "SEP490_G57"."driver_profiles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."driver_profiles" ADD CONSTRAINT "driver_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "SEP490_G57"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicles" ADD CONSTRAINT "vehicles_type_id_fkey" FOREIGN KEY ("type_id") REFERENCES "SEP490_G57"."vehicle_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."vehicles" ADD CONSTRAINT "vehicles_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "SEP490_G57"."driver_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."seat_templates" ADD CONSTRAINT "seat_templates_vehicle_type_id_fkey" FOREIGN KEY ("vehicle_type_id") REFERENCES "SEP490_G57"."vehicle_types"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."booking_seats" ADD CONSTRAINT "booking_seats_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "SEP490_G57"."bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."accounts" ADD CONSTRAINT "fk_accounts_user" FOREIGN KEY ("user_id") REFERENCES "SEP490_G57"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SEP490_G57"."wallet_transactions" ADD CONSTRAINT "wallet_transactions_wallet_id_fkey" FOREIGN KEY ("wallet_id") REFERENCES "SEP490_G57"."wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
